spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/assistant?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
server:
  port: 9099
  servlet:
    context-path: /assistant