spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/reg_sys
    username: regUser
    password: regUser
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
server:
  port: 8081
  context-path: /regsys

